title: DNS Server
description: Block ads and malwares at DNS level with your private DNS Server
url: https://joxit.dev/dns-server
google_analytics: G-T158HYBVZ2
remote_theme: joxit/joxit.github.io
author: Jones Magloire
twitter:
  username: Joxit
instagram:
  username: jox.it
plugins:
  - jekyll-seo-tag