name: Push on docker hub

on:
  push:
    tags: ['*']
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Major tag
      id: major-tag
      run: echo "::set-output name=tag::$(git describe --tags | grep -o '^[0-9]*')"
    - name: Minor tag
      id: minor-tag
      run: echo "::set-output name=tag::$(git describe --tags | grep -o '^[0-9]*\.[0-9]*')"
    - name: Patch tag
      id: patch-tag
      run: echo "::set-output name=tag::$(git describe --tags | grep -o '^[0-9]*\.[0-9]*\.[0-9]*')"
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build DNS Server
      run: cargo build --release
    - name: Tests DNS Server
      run: cargo test
    - name: Build image latest/tag and push
      if: github.ref != 'refs/heads/main'
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/386,linux/amd64,linux/arm64
        push: true
        tags: |
          joxit/dns-server:latest
          joxit/dns-server:${{steps.major-tag.outputs.tag}}
          joxit/dns-server:${{steps.minor-tag.outputs.tag}}
          joxit/dns-server:${{steps.patch-tag.outputs.tag}}
    - name: Build image main and push
      if: github.ref == 'refs/heads/main'
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/386,linux/amd64,linux/arm64
        push: true
        tags: |
          joxit/dns-server:main